// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSICAbpJtRKPzSlYvae0FOtfqq4f6Oxs',
    appId: '1:751388705409:web:4d46d3e0b7bed426d10380',
    messagingSenderId: '751388705409',
    projectId: 'myfirebasechat-9b6a4',
    authDomain: 'myfirebasechat-9b6a4.firebaseapp.com',
    databaseURL: 'https://myfirebasechat-9b6a4-default-rtdb.firebaseio.com',
    storageBucket: 'myfirebasechat-9b6a4.appspot.com',
    measurementId: 'G-HEJMWL16MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9htlpGs_kCZz0DqpN4-hK_2VuHPlqmSc',
    appId: '1:751388705409:android:da8fefa1c4d40e6cd10380',
    messagingSenderId: '751388705409',
    projectId: 'myfirebasechat-9b6a4',
    databaseURL: 'https://myfirebasechat-9b6a4-default-rtdb.firebaseio.com',
    storageBucket: 'myfirebasechat-9b6a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnBVC4-21wXH47W1Zq8XOJCSXkcR-WxH8',
    appId: '1:751388705409:ios:ae1dd8a78a907343d10380',
    messagingSenderId: '751388705409',
    projectId: 'myfirebasechat-9b6a4',
    databaseURL: 'https://myfirebasechat-9b6a4-default-rtdb.firebaseio.com',
    storageBucket: 'myfirebasechat-9b6a4.appspot.com',
    androidClientId: '751388705409-9mppck5tb9v644d7nku1cr1s1uu8n9os.apps.googleusercontent.com',
    iosClientId: '751388705409-2t8i0g8mt157r284nhhjgpn4junfrl4q.apps.googleusercontent.com',
    iosBundleId: 'com.drsync.chattingApp',
  );
}
